POST http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3R1c2VyIiwiaWQiOiI1Y2YzY2ZjN2IwYmMzMzM1YjgwYjI5MTUiLCJpYXQiOjE1NTk3NTQ4ODV9.7swOPWUZDjCrnkIORYIFkyXX8UBtFqVposTu1wYrqQc

{
        "title": "Go To Statement Considered Harmful",
        "author": "Edsger W. Dijkstra",
        "url": "http://www.u.arizona.edu/~rubinson/copyright_violations/Go_To_Considered_Harmful.html",
        "likes": 5
}